### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 9il**
1. I have updated only the first example. It contains comments. You may want them cut and place in the blog post body.
2. LDC has `-betterC` flag now, so you do not need `LDC_no_module_info` anymore.
3. `nm` allows to show to user object file internals. This is important to understand how things works, without any compiler magic.
4. Please add appropriate attributes like `nothrow @nogc`. All C libraries contains only `nothrow @nogc`, some of them are `pure` and/or `@safe`.
5. Please avoid using of Phobos and Druntime. Lets make all examples betterC! So users would have  deeper betterC experience after the blog post. You may use mir-algorithm to replace Phobos.
6. Do you plan to use your blog post or Mir blog? Both variants are fine.

### CODE REVIEW

**Comment by dataPulverizer** [comment]
Thanks for the updates. I would be happy for both of us to put the blog on our websites and share authorship

**Comment by dataPulverizer** [comment]
p.s. At the moment I would like to keep the tutorial without dependencies and as simple as possible. We can do the next article on your Mir library. I shall amend the text as appropriate

**Comment by 9il** [comment]
Then we can avoid both Phobos and Mir

**Comment by dataPulverizer** [comment]
Sounds good, maybe you could write a section on creating your own `writeln` function :-)

In fact you could demonstrate writing a templated map function that we will use in one of the examples

**Comment by 9il** [comment]
`writeln` from scratch is too complex for one section, we can use C `printf` instead

**Comment by dataPulverizer** [comment]
That's actually a good idea, it can be one of the functions that we port from C as an example

**Comment by 9il** [comment]
> That's actually a good idea, it can be one of the functions that we port from C as an example

It is already declared so in this PR

**Comment by dataPulverizer** [comment]
Oh, I see it, my bad! Could you please add the `printf` function back in and also insert simple implementation of a `map` function that we use in the first example? The map function need only return an array.

**Comment by 9il** [comment]
If you do not want to to have external dependencies lets just use plain `foreach` loops without functional programming. This would be more obvious for non D users

**Comment by dataPulverizer** [comment]
True, using `foreach` would be simpler. Do you want to make the adjustment or shall I?

**Comment by 9il** [comment]
Please do

**Comment by dataPulverizer** [comment]
Shall I put back `pure`, `@safe` and `@nogc` or shall we leave that for a different article?

**Comment by dataPulverizer** [comment]
If we put it in now we would need to explain it or we could leave it for a more advanced topic.

**Comment by 9il** [comment]
Lets just add only `@nogc` `nothrow` with simple explanation that C  does not have GC and Exceptions. And we can mark the code them with them.

**Comment by dataPulverizer** [comment]
Done. I also amended the the code in the script folder. Please take a look and let me know if you think we need more changes.

**Comment by dataPulverizer** [comment]
I want to do an article about solving a GLM problem using stochastic gradient descent in D but it has to be a simple clear procedure. Perhaps we can use some elements of Mir, Fortran, C and so on. What do you think?

**Comment by 9il** [comment]
> I want to do an article about solving a GLM problem using stochastic gradient descent in D but it has to be a simple clear procedure. Perhaps we can use some elements of Mir, Fortran, C and so on. What do you think?

This would be good real world example.
- Generic version of algorithm written in D + Mir.
- `float` and `double` instantiation for C and Fortran using mixins.
- Call examples from C and Fortran.

**Comment by 9il** [comment]
D has `ref` parameter qualifier comparing with C. Please change `double*` to `ref double`. This will look more convenient.

**Comment by 9il** [comment]
Lets will post the article in your blog. I will make one-sentences blog post in Mir Blog with a link to your website.

**Comment by dataPulverizer** [comment]
I didn't know that you could substitute `ref` with pointers for function arguments, that's a new one for me. That is now updated.

I didn't realise that you used `scope` in the `printf` reference `int printf(scope const char* format, ...);` why is scope used here?

**Comment by 9il** [comment]
because `printf` does not preserve the pointer internally. So we can free the pointer after printf call.

**Comment by dataPulverizer** [comment]
Does that mean that `scope` limits the argument type only to the function call?

**Comment by 9il** [comment]
Yes

**Comment by dataPulverizer** [comment]
Great. I shall put the blog up on my website and provide the link. Then we can start working on the next one.

**Comment by 9il** [comment]
Please give me a time to review this one

**Comment by dataPulverizer** [comment]
Okay. Please let me know when you are done.

**Comment by 9il** [comment]
> LDC has -betterC flag now, so you do not need LDC_no_module_info anymore.
> nm allows to show to user object file internals. This is important to understand how things works, without any compiler magic.

@dataPulverizer please apply this comment to the article. It is very important to show object file content with `nm`. Also `-linkonce-templates` removes template bloat.

Please add mixins to `Calling D functions from C`. Template `mult` should have `version(LDC) pragma(inline, true); `.

After that I will review once again. Next we need to post a link to the article in General forum to preview, after few days in Announce forum.

**Comment by dataPulverizer** [comment]
Okay, I think we need to restructure the article. Each part should start with a syntactically easy approach even using a bit of Phobos in parts and then a more advanced part to strip out Phobos and add other concepts such as `@nogc`, `nothrow`, `nm`, `-linkonce-templates`, `pragma` and so on.

We can use `-betterC` everywhere as you suggested and remove mention of `pragma(LDC_no_moduleinfo)`. I shall also make it explicit that we will be using the `LDC` compiler.

As for the `Calling D functions from C`, maybe we only need to use:

```
extern (C) nothrow @nogc:

/* Template to generate string */
template GenWrap(string type)
{
	enum string GenWrap = type ~ " " ~ type[0] ~ "mult(" ~ type ~ " x, " ~ type ~ " y)\n{\n\treturn x*y;\n}";
}

mixin(GenWrap!"double");
mixin(GenWrap!"float");
```

on the D side. Let me know if there is a way of doing something similar using templates. One problem I found about exporting templates instances to C is that something like the code below will not work:

```
extern (C) nothrow @nogc:
T mult(T)(T x, T y)
{
	return x*y;
}

alias dmult = mult!double;
alias fmult = mult!float;
```

**Comment by 9il** [comment]
> Each part should start with a syntactically easy approach even using a bit of Phobos in parts

Phobos is easy for D users. In other hand C and C++ users do not know Phobos. The number of C/C++ users one order larger then D users. My goal for articles is to attract С/С++ users instead of urge existing D users. Phobosless code should be OK both for existing and future users.

> One problem I found about exporting templates instances to C is that something like the code below will not work:

This code generates extern(D) names. This is issue. This code should NOT generate anything (Andrei has the same opinion).

> As for the Calling D functions from C, maybe we only need to use:

We need to add different prefixes `s`, `d` for example. Please see https://github.com/libmir/mir-glas/blob/master/source/glas/internal/l1_.d and prefix from https://github.com/libmir/mir-glas/blob/master/source/glas/internal/utility.d

**Comment by dataPulverizer** [comment]
>Phobos is easy for D users. In other hand C and C++ users do not know Phobos. The number of C/C++ users one order larger then D users. My goal for articles is to attract С/С++ users instead of urge existing D users. Phobosless code should be OK both for existing and future users.

Hmm. I am trying to attract R, Python, Julia and programmers that use Scala Spark **and** C/C++ programmers. In my opinion, programmers from those domain specific languages write code in a way that is easily adaptable to Phobos style for instance using some functional style elements. I am trying to demonstrate the case for D - that you can write high-level code and then "open the bonnet" and have low-level access and do the same things as in C/C++ without Phobos.

My goal is to "sell" D as being able to replace R, Python and so on but also for C/C++

>We need to add different prefixes s, d for example. Please see https://github.com/libmir/mir-glas/blob/master/source/glas/internal/l1_.d and prefix from https://github.com/libmir/mir-glas/blob/master/source/glas/internal/utility.d

The code I pasted already does this in the `" " ~ type[0] ~ "mult` part. We can use the `q{}` notation if you prefer.

**Comment by 9il** [comment]
> My goal is to "sell" D as being able to replace R, Python and so on but also for C/C++

If you want to sell it as R or Python that you may want to write an article about mir.ndslice.topology, mir.ndslice.dynamic and other ndslice modules, also mir.random.

The features you describing in this article are for backend development.

People like simple things (Julia) and crazy solutions (Scala), they do not like complex things like high level D. This is a reason why D is not popular. D devs are trying to sell it as better Python and better Java, instead of the best low level language. I am not against better Python and better Java/Scala concepts. But first we need to cover C/C++. Scala is more generic, is more elegant then D, furthermore because JIT is sometimes faster then idiomatic Phobos code. Lets do this without Phobos, if you want to show high level functional code we can write another article.

**Comment by dataPulverizer** [comment]
>If you want to sell it as R or Python that you may want to write an article about mir.ndslice.topology, mir.ndslice.dynamic and other ndslice modules, also mir.random.

I think this is a good idea

> ... JIT is sometimes faster then idiomatic Phobos code

I did not know this. The times I have written code in Scala and compared it with D, I have always found Scala much slower usually about x4. Are there examples or instances when Scala can be faster? I would be very interested in those.

> Scala is more generic, is more elegant then D, ...

Okay, my opinion is a little different. I think Scala has very interesting features some of which I wish where in D. However Scala feels quite clunky to me and still has Java's OOP style plaguing it, it claims to allow C-style but is not really and there is too much "obscura" for my liking. I'll write it if I have too but won't be smiling about it. In addition variadic templates are absent from Scala as is tail recursion and pure functions - strange for a programming language whose main selling point is functional programming. I have been bitten in the past in Scala where `pure` enforcement would have been prevented the bug. However when I mentioned Scala I was specifically talking about Spark ... I am hoping that one day D will have something similar (but better!) for big data computing.

**For me** D feels quite freeing, I can write in an OOP style if I need to, C++ style, a functional style, and then C style. I can do those all independently and they fit together nicely as well

> This is a reason why D is not popular

I don't know, my personal opinion is that D is not popular because:

* It is trying to occupy a space that is filled by BIG hitters, C, C++, and Java which are very entrenched and are not going anywhere.

* There is no organisation currently backing it. Remember that Scala was created and backed by the EU, and very large companies, every other competitor has this advantage.

* Lack of high quality advanced materials. Ali's book is a brilliant introduction, but if you don't already have a C/C++ background, you need much more advanced material which is absent.

* Lack of high quality libraries to attract users to the language (probably a result of the above reasons).

But those may be resulting from another reason ...

> But first we need to cover C/C++

If someone is already a C/C++ programmer would they gain much by moving to D? I think its a hard sell for people already in that world.

I think that D's syntax is simple enough for people already writing languages like R, Python and Julia to adopt. They can start writing easy D code and increase their knowledge with more advanced materials as they go along and write more optimised code if they want all in the same language, call C/Fortran libraries and so on.

My opinion is that you need a static programming language to write robust code, Julia is challenging that but my suspicion is that static will win out, I guess we will see. But I don't think anyone would dream of writing BLAS in Julia, but it can be done in a performant way in D. You have shown that.

In terms of usability in that space, the advantage of the other languages is that they have interpreters, which is invaluable when doing analysis.

Where do you see D's use case?

**Comment by 9il** [comment]
> If someone is already a C/C++ programmer would they gain much by moving to D?

Workforce performance with D is significantly better.

> You have shown that.

It us possible because GLAS is based on betterC D subset.

> There is no organisation currently backing it. Remember that Scala was created and backed by the EU, and very large companies, every other competitor has this advantage.

Good point. Scala was created for business. To be honest D was created for fun.

> Where do you see D's use case?

In low lever programming to replace C. D can be successful high level language if and only if it is successful low level language. But no one cares about how to show D's low lever features for math, numeric, C/Fortran, and hight performance worlds. Everyone tries to provide high level API in their libraries, examples, and books. As result D is a language for small utilities without large libraries that are used in _other_ languages.

I am not against Phobos. But placing Phobos in examples for betterC and integration with other languages is not good because Phobos runtime dependency is not clear and stable. Mir Algorithm was designed as betterC alternative to Phobos. If you do not want to have dependencies lets just use loops. I do not think this is problem.

**Comment by 9il** [comment]
> However when I mentioned Scala I was specifically talking about Spark ... I am hoping that one day D will have something similar (but better!) for big data computing.

I have done Spark analog in D as commercial project. It is a large distributes closed source project for IMO messenger. First it was vibe.d based. Then I release that vibe.d bugs are endless and rewrote the project using Unix sockets. So, the _best_ D project (vibe.d) is useless for large commercial projects. I want D go another way then Phobos/vibe.d offers, more conservative and advanced in the same time.

**Comment by dataPulverizer** [comment]
>  I want D go another way then Phobos/vibe.d offers, more conservative and advanced in the same time.

Okay. Now that we both realise that we were trying to achieve different things I know where the confusion was. I would be willing to use your approach if you still want to continue. If so the best thing is probably for you to amend the code in the article - I have already made changes so maybe you could submit a new PR with what you would regard as the right way to do each task and we can chat about the best way to present it to the reader.

**Pull request merged**
